### ISSUE TITLE
[install] `uv tool install aelix@latest` rebuilds on 3.14 and overwrites a correct 3.13 install — no installer script can cover this

### ISSUE THREAD

**Issue by handochan** [handochan/aelix-ai#278]
Found while reviewing #263. **#263 does not close this, and #192 will not either.**

## What happens

Measured at `501a831`, isolated `UV_TOOL_DIR` each time, against the published `v0.1.0-beta.2`:

```
$ uv tool install aelix@latest
  → version_info = 3.14.5

$ uv tool install --force 'aelix==0.1.0b2'      # onto an env install.sh built on 3.13.13
  before: version_info = 3.13.13
  after : version_info = 3.14.5
```

The second one is the bad one: a single `--force` reinstall **silently overwrites a correct install** with a broken one.

On 3.14 the pinned `openai<2.0` raises, mid-turn:

```
AttributeError: 'typing.Union' object has no attribute '__discriminator__'
                and no __dict__ for setting new attributes
```

That is #262. It is latent — `construct_type` validates through pydantic first and only falls through to the failing write when validation fails — so `-p "reply with exactly: OK"` succeeds on 3.14 and real agent work does not.

## The user is actively routed there

`uv tool upgrade aelix` prints, unprompted:

> hint: `aelix` is pinned to `0.1.0b2` (installed with an exact version pin); reinstall with `uv tool install aelix@latest` to upgrade to a new version.

So uv itself hands the user the command that breaks them.

## Why neither open issue closes it

**#263** put `--python '>=3.11,<3.14'` in `install.sh` / `install.ps1`. That only covers the curl line. A script cannot cover commands the user types directly.

**#192** plans `requires-python = ">=3.11,<3.14"` in the five `pyproject.toml` files. That does **not** bind this path. `uv tool install` chooses the interpreter **before** it resolves, so a published wheel's own ceiling never steers it. Measured against one wheel declaring `Requires-Python: <3.14,>=3.11`:

| how it is installed | interpreter |
| --- | --- |
| `uv tool install --find-links <dir> pkg==0.1.0` | **3.14.5**, exit 0, and the package imports there |
| `uv tool install <the .whl file>` | **3.14.5** |
| `uv tool install <a local project dir>` | 3.13.13 — the only path that reads the ceiling |
| `pip install --find-links <dir> pkg` | refuses: *requires a different Python* |

#192's bound is still worth having — it is what makes `pip install aelix` refuse cleanly — but **#192 should not be planned as though it closes this.**

## Suggested fix

A startup guard in aelix: refuse, or warn loudly, on `sys.version_info >= (3, 14)` while `openai<2.0` is pinned, naming #262.

Two things it buys beyond covering this path:

1. It converts a latent mid-turn `AttributeError` from inside a vendored SDK into a **first-second failure with a cause**.
2. It is the only mechanism that survives however the user installed.

Open questions for whoever takes it:

- Hard refuse or warn? A refuse is honest but strands someone who only uses Anthropic/Gemini, which are unaffected (`anthropic` 0.102.0 and `google-genai` declare the same `CachedDiscriminatorType` protocol and never assign to it — source-level claim; neither was exercised live on 3.14).
- Where does it live? It is a property of the `openai` pin in `aelix-ai`, but the natural place to fail is the `aelix` console script in `aelix-coding-agent`.
- It must lift itself when the pin moves. #262's fix is `openai>=2.7.2` (measured: 2.7.1 still has the write, 2.7.2 does not), so the guard should key off the installed `openai` version rather than a hard-coded Python version.

## Related

- #262 — the crash
- #263 — the installer half, shipped in `501a831`
- #192 — the `requires-python` bound + CI matrix
- ADR-0241 §"What this does NOT close"

🤖 Generated with [Claude Code](https://claude.com/claude-code)
